# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\1_kaoyan\college_ending\college_ending_code\9.Qt_suanfa\_1_直接展示\tu_jiemian.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1270, 759)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(40, 130, 1141, 611))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.button_yuantu = QtWidgets.QPushButton(self.tab)
        self.button_yuantu.setGeometry(QtCore.QRect(60, 70, 231, 91))
        self.button_yuantu.setObjectName("button_yuantu")
        self.button_loftu = QtWidgets.QPushButton(self.tab)
        self.button_loftu.setGeometry(QtCore.QRect(60, 210, 231, 91))
        self.button_loftu.setObjectName("button_loftu")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "窃电分析成果展示"))
        self.button_yuantu.setText(_translate("Dialog", "原图"))
        self.button_loftu.setText(_translate("Dialog", "LOF图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "拉合闸"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "用电量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "三相电压"))
